(add-to-list 'load-path (concat user-emacs-directory "config"))

(require 'packages)
(require 'base)
(require 'completion)
(require 'keymappings)
(require 'vim)
(require 'workspace)
(require 'lang)
(require 'lang-go)
(require 'lang-rust)
(require 'font)
(require 'theme)
(require 'splash)
(require 'path)
(require 'discord)
